/* ---------------------------------------------------------------- */
/* Creación de ESQUEMAS (mismo concepto que base de datos en mysql) */
/* ---------------------------------------------------------------- */
CREATE SCHEMA STAGING;
CREATE SCHEMA MAESTROS;
CREATE SCHEMA COMERCIAL;

/* ------------------ */
/* Creación de TABLAS */
/* ------------------ */

/* STAGING */
CREATE TABLE STAGING.AUX_CARGA_DW (
ID_CARGA_DW int,
ID_FECHA date,
DESCRIPCION varchar(30) not null,
INICIO datetime not null,
FIN datetime,
USUARIO_ALTA varchar(20),
PRIMARY KEY (ID_CARGA_DW, ID_FECHA);

CREATE TABLE STAGING.AUX_FACT_VENTA (
ID_VENTA bigint not null,
FECHA_HORA datetime,
NUM_TICKET bigint,
ID_ARTICULO int,
ID_TIPO_PRODUCTO int,
ID_MARCA int,
ID_TIENDA int,
ID_SECCION int,
ID_PERIODO int,
ID_CAMPANA int,
PRECIO_UNITARIO float(5,2)
UNIDADES int,
PRECIO float(5,2)
FECHA_ALTA datetime,
USUARIO_ALTA varchar(20) );

CREATE TABLE STAGING.AUX_INSERTA_FACT_VENTA (
COD_VENTA bigint not null,
FECHA_HORA datetime,
ID_FECHA date not null,
ID_MES int not null,
ID_TRIMESTRE int not null,
ID_SEMESTRE int not null,
ID_ANO int not null,
ID_ARTICULO int not null,
ID_TIPO_PRODUCTO int not null,
ID_MARCA int not null,
ID_TIENDA int not null,
ID_PROVINCIA int not null,
ID_PAIS int not null,
ID_ZONA int not null,
ID_SECCION int not null,
ID_PERIODO int not null,
ID_CAMPANA int not null,
PRECIO_UNITARIO float(5,2)
UNIDADES int,
PRECIO float(5,2)
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null );

CREATE TABLE STAGING.AUX_MMTT (
ID_TIENDA int,
ID_FECHA int,
MMTT_DIA bit not null,
MMTT_DIA_POST bit not null,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20)
PRIMARY KEY (ID_TIENDA, ID_FECHA) );

CREATE TABLE STAGING.AUX_MMTT_MES (
ID_TIENDA int,
ID_MES int,
ID_ANO int,
MMTT_MES bit not null,
MMTT_MES_POST bit not null,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
PRIMARY KEY (ID_TIENDA, ID_MES, ID_ANO) );

CREATE TABLE STAGING.AUX_MMTT_TRIMESTRE (
ID_TIENDA int,
ID_TRIMESTRE int,
ID_ANO int,
MMTT_TRIMESTRE bit not null,
MMTT_TRIMESTRE_POST bit not null,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20)
PRIMARY KEY (ID_TIENDA, ID_TRIMESTRE, ID_ANO) );

/* MAESTROS */
CREATE TABLE MAESTROS.DIM_FECHA (
ID_FECHA date,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
PRIMARY KEY (ID_FECHA) );

CREATE TABLE MAESTROS.DIM_MES (
ID_MES int,
DESC_MES varchar(10),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_MES) );
  
CREATE TABLE MAESTROS.DIM_TRIMESTRE (
ID_TRIMESTRE int,
DESC_TRIMESTRE varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_TRIMESTRE) );

CREATE TABLE MAESTROS.DIM_SEMESTRE (
ID_SEMESTRE int,
DESC_SEMESTRE varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_SEMESTRE) );

CREATE TABLE MAESTROS.DIM_ANO (
ID_ANO int,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
PRIMARY KEY (ID_ANO) );

CREATE TABLE MAESTROS.DIM_TIENDA (
ID_TIENDA int auto_increment,
COD_TIENDA int,
DESC_TIENDA varchar(30),
DIRECCION varchar(30),
LATITUD int,
LONGITUD int,
FECHA_APERTURA date,
FECHA_CIERRE date,
FECHA_ULT_REF date,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_TIENDA) );

CREATE TABLE MAESTROS.DIM_PROVINCIA (
ID_PROVINCIA int auto_increment,
COD_PROVINCIA int,
DESC_PROVINCIA varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_PROVINCIA) );

CREATE TABLE MAESTROS.DIM_PAIS (
ID_PAIS int auto_increment,
COD_PAIS int,
DESC_PAIS varchar(20),
CODIGO_ISO varchar(2),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_PAIS) );

CREATE TABLE MAESTROS.DIM_ZONA (
ID_ZONA int auto_increment,
COD_ZONA int,
DESC_ZONA varchar(20),
COD_RESPONSABLE int,
NOMBRE_RESPONSABLE varchar(20),
APELLIDO1_RESPONSABLE varchar(20),
APELLIDO2_RESPONSABLE varchar(20),
DNI_RESPONSABLE	varchar(15),
FECHA_DESDE	date,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_ZONA) );

/* COMERCIAL */
CREATE TABLE COMERCIAL.DIM_PERIODO (
ID_PERIODO int auto_increment,
COD_PERIODO int,
DESC_PERIODO varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_PERIODO) );

CREATE TABLE COMERCIAL.DIM_CAMPANA (
ID_CAMPANA int auto_increment,
COD_CAMPANA int,
DESC_CAMPANA varchar(5),
COD_TIPO_CAMPANA int,
DESC_TIPO_CAMPANA varchar(20),
ANO_CAMPANA int,
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_CAMPANA) );

CREATE TABLE COMERCIAL.DIM_SECCION (
ID_SECCION int auto_increment,
COD_SECCION int,
DESC_SECCION varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_SECCION) );

CREATE TABLE COMERCIAL.DIM_ARTICULO (
ID_ARTICULO int auto_increment,
COD_ARTICULO int,
DESC_ARTICULO varchar(50),
COD_MODELO int,
DESC_MODELO varchar(50),
COD_COLOR int,
DESC_COLOR varchar(20),
COD_TALLA int,
DESC_TALLA varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_ARTICULO) );

CREATE TABLE COMERCIAL.DIM_TIPO_PRODUCTO (
ID_TIPO_PRODUCTO int auto_increment,
COD_TIPO_PRODUCTO int,
DESC_TIPO_PRODUCTO varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_TIPO_PRODUCTO) );

CREATE TABLE COMERCIAL.DIM_MARCA (
ID_MARCA int auto_increment,
COD_MARCA int,
DESC_MARCA varchar(20),
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
FECHA_MODIFICACION datetime,
USUARIO_MODIFICACION varchar(20),
PRIMARY KEY (ID_MARCA) );

CREATE TABLE COMERCIAL.FACT_VENTA (
COD_VENTA bigint not null,
FECHA_HORA datetime,
ID_FECHA date not null,
ID_MES int not null,
ID_TRIMESTRE int not null,
ID_SEMESTRE int not null,
ID_ANO int not null,
ID_ARTICULO int not null,
ID_TIPO_PRODUCTO int not null,
ID_MARCA int not null,
ID_TIENDA int not null,
ID_PROVINCIA int not null,
ID_PAIS int not null,
ID_ZONA int not null,
ID_SECCION int not null,
ID_PERIODO int not null,
ID_CAMPANA int not null,
PRECIO_UNITARIO float(5,2)
UNIDADES int,
PRECIO float(5,2)
FECHA_ALTA datetime not null,
USUARIO_ALTA varchar(20) not null,
INDEX (ID_TIENDA),
INDEX (ID_FECHA),
INDEX (ID_ANO),
FOREIGN KEY (ID_FECHA) REFERENCES MAESTROS.DIM_FECHA(ID_FECHA),
FOREIGN KEY (ID_MES) REFERENCES MAESTROS.DIM_MES(ID_MES),
FOREIGN KEY (ID_TRIMESTRE) REFERENCES MAESTROS.DIM_TRIMESTRE(ID_TRIMESTRE),
FOREIGN KEY (ID_SEMESTRE) REFERENCES MAESTROS.DIM_SEMESTRE(ID_SEMESTRE),
FOREIGN KEY (ID_ANO) REFERENCES MAESTROS.DIM_ANO(ID_ANO),
FOREIGN KEY (ID_ARTICULO) REFERENCES MAESTROS.DIM_ARTICULO(ID_ARTICULO),
FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES MAESTROS.DIM_TIPO_PRODUCTO(ID_TIPO_PRODUCTO),
FOREIGN KEY (ID_MARCA) REFERENCES MAESTROS.DIM_MARCA(ID_MARCA),
FOREIGN KEY (ID_TIENDA) REFERENCES MAESTROS.DIM_TIENDA(ID_TIENDA),
FOREIGN KEY (ID_PROVINCIA) REFERENCES MAESTROS.DIM_PROVINCIA(ID_PROVINCIA),
FOREIGN KEY (ID_PAIS) REFERENCES MAESTROS.DIM_PAIS(ID_PAIS),
FOREIGN KEY (ID_ZONA) REFERENCES MAESTROS.DIM_ZONA(ID_ZONA),
FOREIGN KEY (ID_SECCION) REFERENCES MAESTROS.DIM_SECCION(ID_SECCION),
FOREIGN KEY (ID_PERIODO) REFERENCES MAESTROS.DIM_PERIODO(ID_PERIODO),
FOREIGN KEY (ID_CAMPANA) REFERENCES MAESTROS.DIM_CAMPANA(ID_CAMPANA)
 );

