CREATE PROCEDURE 1_1_2_Carga_AUX_FACT_VENTA ()
BEGIN
  TRUNCATE TABLE STAGING.AUX_FACT_VENTA;
  
  INSERT INTO STAGING.AUX_FACT_VENTA
    SELECT (ID_VENTA, FECHA_HORA, NUM_TICKET, ID_ARTICULO, ID_TIPO_PRODUCTO, ID_MARCA, ID_TIENDA,ID_SECCION, ID_PERIODO, ID_CAMPANA, PRECIO_UNITARIO, UNIDADES, PRECIO, FECHA_ALTA, USUARIO_ALTA)
    FROM CONTROL_VENTAS@operacional CV 
    INNER JOIN VENTA@operacional V ON (CV.ID_VENTA=V.ID_VENTA AND CV.CARGA_DW=2);
  COMMIT;
END;