CREATE PROCEDURE 1_2_5_Carga_DIM_ZONA ()
BEGIN

  /* Se crea una tabla temporal con la información de las tablas ZONA, ZONA_RESPONSABLE Y EMPLEADO del operacional, puesto que se desnormalizan en su paso al DWH */
  CREATE TEMPORARY TABLE temp_zona_resp (
  ID_ZONA int,
  DESCRIPCION varchar(20),
  ID_RESPONSABLE int,
  FECHA_DESDE date,
  NOMBRE varchar(20),
  APELLIDO1 varchar(20),
  APELLIDO2 varchar(20),
  DNI varchar(15)
  );
  INSERT INTO temp_zona_resp (ID_ZONA, DESCRIPCION, ID_RESPONSABLE, FECHA_HASTA, NOMBRE, APELLIDO1, APELLIDO2, DNI)
    SELECT Z.ID_ZONA, Z.DESCRIPCION, ZR.ID_RESPONSABLE, ZR.FECHA_DESDE, E.NOMBRE, E.APELLIDO1, E.APELLIDO2, DNI
    FROM ZONA@operacional Z
    LEFT JOIN ZONA_RESPONSABLE@operacional ZR ON (Z.ID_ZONA=ZR.ID_ZONA AND ZR.FECHA_HASTA is null)
    LEFT JOIN EMPLEADO@operacional E ON (ZR.ID_RESPONSABLE=E.ID_EMPLEADO);
  /* Se actualizan los registros que coinciden en la tabla operacional con la tabla temporal */
  UPDATE MAESTROS.DIM_ZONA 
  INNER JOIN temp_zona_resp Z
  ON COD_ZONA=Z.ID_ZONA
  SET DESC_ZONA=Z.DESCRIPCION,
      COD_RESPONSABLE=Z.ID_RESPONSABLE,
	  NOMBRE_RESPONSABLE=Z.NOMBRE,
	  APELLIDO1_RESPONSABLE=Z.APELLIDO1,
	  APELLIDO2_RESPONSABLE=Z.APELLIDO2,
	  DNI_RESPONSABLE=Z.DNI,
	  FECHA_DESDE=Z.FECHA_DESDE,
	  FECHA_MODIFICACION=current_timestamp,
	  USUARIO_MODIFICACION=current_user;
  COMMIT;
  /* Se insertan los registros nuevos */
  INSERT INTO MAESTROS.DIM_ZONA (COD_ZONA, DESC_ZONA, COD_RESPONSABLE, NOMBRE_RESPONSABLE, APELLIDO1_RESPONSABLE, APELLIDO2_RESPONSABLE, DNI_RESPONSABLE, FECHA_DESDE, FECHA_ALTA, USUARIO_ALTA)
    SELECT Z.ID_ZONA, Z.DESCRIPCION, Z.ID_RESPONSABLE, Z.NOMBRE, Z.APELLIDO1, Z.APELLIDO2, Z.DNI, Z.FECHA_DESDE, current_timestamp, current_user
    FROM temp_zona_resp Z
    LEFT JOIN MAESTROS.DIM_ZONA DZ
    ON Z.ID_ZONA=DZ.COD_ZONA
    WHERE DZ.ID_ZONA IS NULL;
  COMMIT;
END;