CREATE PROCEDURE 1_2_4_Carga_DIM_PROVINCIA ()
BEGIN
  /* Se actualizan los registros que coinciden en la tabla operacional con la dimensión */
  UPDATE MAESTROS.DIM_PROVINCIA 
  INNER JOIN PROVINCIA@operacional P
  ON COD_PROVINCIA=P.ID_PROVINCIA
  SET DESC_PROVINCIA=P.DESCRIPCION,
	  FECHA_MODIFICACION=current_timestamp,
	  USUARIO_MODIFICACION=current_user;
  COMMIT;
  /* Se insertan los registros nuevos */
  INSERT INTO MAESTROS.DIM_PROVINCIA (COD_PROVINCIA, DESC_PROVINCIA, FECHA_ALTA, USUARIO_ALTA)
    SELECT P.ID_PROVINCIA, P.DESCRIPCION, current_timestamp, current_user
    FROM PROVINCIA@operacional P
    LEFT JOIN MAESTROS.DIM_PROVINCIA DP
    ON P.ID_PROVINCIA=DP.COD_PROVINCIA
    WHERE DP.ID_PROVINCIA IS NULL;
  COMMIT;
END;