CREATE PROCEDURE 1_2_11_Carga_DIM_CAMPANA ()
BEGIN
  /* Se crea una tabla temporal con la información de Campaña y Tipo Campaña del operacional */
  CREATE TEMPORARY TABLE temp_camp_tcamp (
  ID_CAMPANA int,
  DESC_CAMPANA varchar(5), 
  ID_TIPO_CAMPANA int,
  DESC_TIPO_CAMPANA varchar(20),
  ANO_CAMPANA int);
  INSERT INTO temp_camp_tcamp (ID_CAMPANA, DESC_CAMPANA, ID_TIPO_CAMPANA, DESC_TIPO_CAMPANA, ANO_CAMPANA)
    SELECT C.ID_CAMPANA, C.DESCRIPCION, C.ID_TIPO_CAMPANA, TC.DESCRIPCION, CAST(SUBSTRING(TC.DESCRIPCION,2,4) AS INT)
	FROM CAMPANA@operacional C
	INNER JOIN TIPO_CAMPANA@operacional TC
	ON C.ID_TIPO_CAMPANA=TC.ID_TIPO_CAMPANA;
	
  /* Se actualizan los registros que coinciden en la tabla operacional con la temporal */
  UPDATE COMERCIAL.DIM_CAMPANA 
  INNER JOIN temp_camp_tcamp T
  ON COD_CAMPANA=T.ID_CAMPANA
  SET DESC_CAMPANA=T.DESC_CAMPANA,
      COD_TIPO_CAMPANA=T.ID_TIPO_CAMPANA,
	  DESC_TIPO_CAMPANA=T.DESC_TIPO_CAMPANA,
	  ANO_CAMPANA=T.ANO_CAMPANA,
	  FECHA_MODIFICACION=current_timestamp,
	  USUARIO_MODIFICACION=current_user;
  COMMIT;
  /* Se insertan los registros nuevos */
  INSERT INTO COMERCIAL.DIM_CAMPANA (COD_CAMPANA, DESC_CAMPANA, COD_TIPO_CAMPANA, DESC_TIPO_CAMPANA, ANO_CAMPANA, FECHA_ALTA, USUARIO_ALTA)
    SELECT T.ID_CAMPANA, T.DESC_CAMPANA, T.ID_TIPO_CAMPANA, T.DESC_TIPO_CAMPANA, T.ANO_CAMPANA, current_timestamp, current_user
    FROM temp_camp_tcamp T
    LEFT JOIN COMERCIAL.DIM_CAMPANA DC
    ON T.ID_CAMPANA=DC.COD_CAMPANA
    WHERE DC.ID_CAMPANA IS NULL;   	
  COMMIT;
END;