CREATE PROCEDURE 1_2_3_Carga_DIM_TIENDA ()
BEGIN
  /* Se actualizan los registros que coinciden en la tabla operacional con la dimensión */
  UPDATE MAESTROS.DIM_TIENDA 
  INNER JOIN TIENDA@operacional T
  ON COD_TIENDA=T.ID_TIENDA
  SET DESC_TIENDA=T.DESCRIPCION,
      DIRECCION=T.DIRECCION,
	  LATITUD=T.LATITUD,
	  LONGITUD=T.LONGITUD,
	  FECHA_APERTURA=T.FECHA_AP,
	  FECHA_CIERRE=T.FECHA_CI,
	  FECHA_ULT_REF=T.FECHA_UR,
	  FECHA_MODIFICACION=current_timestamp,
	  USUARIO_MODIFICACION=current_user;
  COMMIT; 
  /* Se insertan los registros nuevos */
  INSERT INTO MAESTROS.DIM_TIENDA (COD_TIENDA, DESC_TIENDA, DIRECCION, LATITUD, LONGITUD, FECHA_APERTURA, FECHA_CIERRE, FECHA_ULT_REF, FECHA_ALTA, USUARIO_ALTA)
    SELECT T.ID_TIENDA, T.DESCRIPCION, T.DIRECCION, T.LATITUD, T.LONGITUD, T.FECHA_AP, T.FECHA_CI, T.FECHA_UR, current_timestamp, current_user
    FROM TIENDA@operacional T
    LEFT JOIN MAESTROS.DIM_TIENDA DT
    ON T.ID_TIENDA=DT.COD_TIENDA
    WHERE DT.ID_TIENDA IS NULL;
  COMMIT;
END;