CREATE PROCEDURE 1_2_8_Carga_DIM_TIPO_PRODUCTO ()
BEGIN
  /* Se actualizan los registros que coinciden en la tabla operacional con la dimensión */
  UPDATE COMERCIAL.DIM_TIPO_PRODUCTO 
  INNER JOIN TIPO_PRODUCTO@operacional TP
  ON COD_TIPO_PRODUCTO=TP.ID_TIPO_PRODUCTO
  SET DESC_TIPO_PRODUCTO=TP.DESCRIPCION,
	  FECHA_MODIFICACION=current_timestamp,
	  USUARIO_MODIFICACION=current_user;
  COMMIT;
  /* Se insertan los registros nuevos */
  INSERT INTO COMERCIAL.DIM_TIPO_PRODUCTO (COD_TIPO_PRODUCTO, DESC_TIPO_PRODUCTO, FECHA_ALTA, USUARIO_ALTA)
    SELECT TP.ID_TIPO_PRODUCTO, TP.DESCRIPCION, current_timestamp, current_user
    FROM TIPO_PRODUCTO@operacional TP
    LEFT JOIN COMERCIAL.DIM_TIPO_PRODUCTO DTP
    ON TP.ID_TIPO_PRODUCTO=DTP.COD_TIPO_PRODUCTO
    WHERE DTP.ID_TIPO_PRODUCTO IS NULL;  
  COMMIT;
END;